specVersion: 0.2.0
name: acala-incentives
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  endpoint: wss://karura.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/AcalaNetwork/karura-dictionary
  chaintypes:
    file: './src/types.json'
dataSources:
  - kind: substrate/Runtime
    startBlock: 0
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleDepositDexShare
          kind: substrate/EventHandler
          filter:
            module: incentives 
            method: DepositDexShare
        - handler: handleWithdrawDexShare
          kind: substrate/EventHandler
          filter:
            module: incentives 
            method: WithdrawDexShare
        - handler: handlePayoutRewards
          kind: substrate/EventHandler
          filter:
            module: incentives 
            method: PayoutRewards
        - handler: handleClaimRewards
          kind: substrate/EventHandler
          filter:
            module: incentives 
            method: ClaimRewards
