version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node-acala-dex:
    build:
      context: ./packages/dex
      dockerfile: subqueryNode.Dockerfile
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/dex/acala-project.yaml
      - --network-endpoint=wss://acala-polkadot.api.onfinality.io/public-ws,wss://acala.polkawallet.io,wss://acala-rpc-0.aca-api.network
      - --db-schema=acala-dex
      - --schema=acala-dex

  subquery-node-karura-dex:
    build:
      context: ./packages/dex
      dockerfile: subqueryNode.Dockerfile
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/dex/karura-project.yaml
      - --network-endpoint=wss://karura-rpc-0.aca-api.network,wss://karura.api.onfinality.io/public-ws,wss://karura-rpc-1.aca-api.network
      - --db-schema=karura-dex
      - --schema=karura-dex

  graphql-engine-acala-dex:
    build:
      context: ./packages/dex
      dockerfile: graphqlEngine.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - "postgres"
      - "subquery-node-acala-dex"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=acala-dex
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node:3000

  graphql-engine-karura-dex:
    build:
      context: ./packages/dex
      dockerfile: graphqlEngine.Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - "postgres"
      - "subquery-node-karura-dex"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=karura-dex
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node:3000