version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node-acala-dex:
    image: ${SUBQUERY_NODE_IMAGETAG}
    depends_on:
      - "postgres"
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/dex-subql/acala-project.yaml
      - --network-endpoint=${ACALA_ENDPOINT}
      - --db-schema=acala-dex
      - --schema=acala-dex
      - --unsafe

  subquery-node-karura-dex:
    image: ${SUBQUERY_NODE_IMAGETAG}
    depends_on:
      - "postgres"
    restart: always
    ports:
      - 3001:3000
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/dex-subql/karura-project.yaml
      - --network-endpoint=${KARURA_ENDPOINT}
      - --db-schema=karura-dex
      - --schema=karura-dex
      - --unsafe

  graphql-engine-acala-dex:
    image: ${SUBQUERY_IMAGETAG}
    ports:
      - 4000:4000
    depends_on:
      - "postgres"
      - "subquery-node-acala-dex"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=acala-dex
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node-acala-dex:3000

  graphql-engine-karura-dex:
    image: ${SUBQUERY_IMAGETAG}
    ports:
      - 4001:4000
    depends_on:
      - "postgres"
      - "subquery-node-karura-dex"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=karura-dex
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node-karura-dex:3000

  subquery-node-acala-loan:
    image: ${SUBQUERY_NODE_IMAGETAG}
    depends_on:
      - "postgres"
    restart: always
    ports:
      - 3010:3000
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/loan-subql/acala-project.yaml
      - --network-endpoint=${ACALA_ENDPOINT}
      - --db-schema=acala-loan
      - --schema=acala-loan
      - --unsafe

  subquery-node-karura-loan:
    image: ${SUBQUERY_NODE_IMAGETAG}
    depends_on:
      - "postgres"
    restart: always
    ports:
      - 3011:3000
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --subquery=/app/packages/loan-subql/karura-project.yaml
      - --network-endpoint=${KARURA_ENDPOINT}
      - --db-schema=karura-loan
      - --schema=karura-loan
      - --unsafe

  graphql-engine-acala-loan:
    image: ${SUBQUERY_IMAGETAG}
    ports:
      - 4010:4000
    depends_on:
      - "postgres"
      - "subquery-node-acala-loan"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=acala-loan
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node-acala-loan:3000

  graphql-engine-karura-loan:
    image: ${SUBQUERY_IMAGETAG}
    ports:
      - 4011:4000
    depends_on:
      - "postgres"
      - "subquery-node-karura-loan"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=karura-loan
      - --playground
      - --scale-batch-size=true
      - --indexer=http://subquery-node-karura-loan:3000