specVersion: 0.2.0
name: acala-dex
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  dictionary: https://api.subquery.network/sq/subquery/karura-dictionary
  endpoint: wss://karura.api.onfinality.io/public-ws
  chaintypes:
    file: './src/chain-types.js'
dataSources:
    - kind: substrate/Runtime
      startBlock: 2098000
      mapping:
        file: './dist/index.js'
        handlers:
          - handler: handleBalancesDustLost
            kind: substrate/EventHandler
            filter:
              module: balances
              method: DustLost
          - handler: handleBalancesTransfer
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Transfer
          - handler: handleBalancesReserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Reserved
          - handler: handleBalancesUnreserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Unreserved
          - handler: handleBalancesReserveRepatriated
            kind: substrate/EventHandler
            filter:
              module: balances
              method: ReserveRepatriated
          - handler: handleBalancesDeposit
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Deposit
          - handler: handleBalancesWithdraw
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Withdraw
       
          - handler: handleTokensTransfer
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Transfer
          - handler: handleTokensReserved
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Reserved
          - handler: handleTokensUnreserved
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Unreserved
          - handler: handleTokensReserveRepatriated
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: ReserveRepatriated
          - handler: handleTokensDeposited
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Deposited
          - handler: handleTokensWithdrawn
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Withdrawn
          - handler: handleTokensSlashed
            kind: substrate/EventHandler
            filter:
              module: tokens
              method: Slashed